language: python
python:
  - "2.7"
# comando para instalar dependÃªncias
install:
  - ./init.sh
  - "pip install -r requirements.txt --use-mirrors"
# comando para executar testes
script: "python manage.py test"
after_success: coveralls